waypoint_follower:
  delta: 0.1
  lead_distance: 1.0
  follow_distance: 0.8

pose_controller:
  close_distance: 0.05
  close_heading: 0.087266 # 5 degrees
  retry_distance: 2.0
  retry_close: 0.10

saturation:
  velocity_max: 1.0
  velocity_min: -1.0
  steering_max: 0.3

mission:
  waypoints_there:
    # - [0.0, 5.0]
    # - [3.0, 7.0]
    # - [7.0, 7.0]
    # - [7.0, 6.0]
    - [10.0, 1.0]
    - [12.0, 1.0]
  waypoints_back:
    - [12.0, 6.0]
    - [7.0, 6.0]
    - [7.0, 7.0]
    - [3.0, 7.0]
    - [0.0, 5.0]
    - [0.0, 0.0]
  pucker_pose: [13.0, 3.5, 0.0]
  landmarks:
    home: [0.0, 0.0]
    brigham: [15.0, 3.5]
  endgame:
    radius: 3.0
