waypoint_follower:
  delta: 0.1
  lead_distance: 1.0
  follow_distance: 0.8

mission:
  waypoints_there:
    - [0.0, 5.0]
    - [3.0, 7.0]
    - [7.0, 7.0]
    - [7.0, 6.0]
    - [10.0, 1.0]
    - [12.0, 1.0]
    - [13.0, 3.5]
  waypoints_back:
    - [12.0, 6.0]
    - [7.0, 6.0]
    - [7.0, 7.0]
    - [3.0, 7.0]
    - [0.0, 5.0]
    - [0.0, 0.0]
  landmarks:
    home: [0.0, 0.0]
    brigham: [15.0, 3.5]
  endgame:
    heading: 0.0
    radius: 3.0
